server:
  port: 80

spring:
  # 生产环境数据源配置
  datasource:
    url: jdbc:mysql://prod-db:3306/student_prod?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: prod_user
    password: StrongP@ssw0rd!
    druid:
      # 生产环境增加连接池容量
      initial-size: 10
      min-idle: 10
      max-active: 50

# 日志配置
logging:
  level:
    root: warn
    com.example.student: info
  file:
    name: /var/logs/student/student-app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# 禁用MyBatis-Plus SQL日志，提高性能
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl 